//author: Leigh Brown
//the initial habits in the habit tracker table. have been changed slighly with testing.
import {HabitProps} from '@/types';
export const defaultHabits: HabitProps[] = [
    {
        id: 1,
        habit: "Drink Water",
        type: "Health + Wellness",
        tracking: "daily",
        notes: "8 glasses of water a day",
        sun: false,
        mon: false,
        tue: false,
        wed: false,
        thu: false,
        fri: false,
        sat: false,
        weeklyCompleted: 0,

    },
    {
        id: 2,
        habit: "Clean Room",
        type: "Household",
        tracking: "weekly",
        notes: "Sunday reset",
        sun: false,
        mon: false,
        tue: false,
        wed: false,
        thu: false,
        fri: false,
        sat: false,
        weeklyCompleted: 0,

    },
    {
        id: 3,
        habit: "Save $50",
        type: "Finance",
        tracking: "weekly",
        sun: false,
        mon: false,
        tue: false,
        wed: false,
        thu: false,
        fri: false,
        sat: false,
        weeklyCompleted: 0,

    },
    {
        id: 4,
        habit: "Read a Book",
        type: "Personal",
        tracking: "weekly",
        notes: "At least 50 pages per week",
        sun: false,
        mon: false,
        tue: false,
        wed: false,
        thu: false,
        fri: false,
        sat: false,
        weeklyCompleted: 0,

    },
    {
        id: 5,
        habit: "Weekly Planning",
        type: "Productivity",
        tracking: "weekly",
        notes: "Pick day of week to plan for the next week",
        sun: false,
        mon: false,
        tue: false,
        wed: false,
        thu: false,
        fri: false,
        sat: false,
        weeklyCompleted: 0,

    },
    {
        id: 6,
        habit: "blank",
        type: "Productivity",
        tracking: "weekly",
        sun: false,
        mon: false,
        tue: false,
        wed: false,
        thu: false,
        fri: false,
        sat: false,
        weeklyCompleted: 0,

    },
    {
        id: 7,
        habit: "blank",
        type: "Productivity",
        tracking: "weekly",
        sun: false,
        mon: false,
        tue: false,
        wed: false,
        thu: false,
        fri: false,
        sat: false,
        weeklyCompleted: 0,

    },
    {
        id: 8,
        habit: "blank",
        type: "Productivity",
        tracking: "weekly",
        sun: false,
        mon: false,
        tue: false,
        wed: false,
        thu: false,
        fri: false,
        sat: false,
        weeklyCompleted: 0,

    },
    {
        id: 9,
        habit: "blank",
        type: "Productivity",
        tracking: "weekly",
        sun: false,
        mon: false,
        tue: false,
        wed: false,
        thu: false,
        fri: false,
        sat: false,
        weeklyCompleted: 0,

    },
    {
        id: 10,
        habit: "blank",
        type: "Productivity",
        tracking: "weekly",
        sun: false,
        mon: false,
        tue: false,
        wed: false,
        thu: false,
        fri: false,
        sat: false,
        weeklyCompleted: 0,

    },
];